export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER = 'SET_USER';

//new Hindi Playlist

export const SET_NEWMUSIC_HINDI_ALLPLAYLIST = 'SET_NEWMUSIC_HINDI_ALLPLAYLIST';
export const SET_BEST_0F_ARMAAN_MALIK = 'SET_BEST_0F_ARMAAN_MALIK';
export const BOLLYWOOD_ALBUMS = 'BOLLYWOOD_ALBUMS';
export const NEW_HINDI_SONGS = 'NEW_HINDI_SONGS';


// Beats

export const LO_FI_BEATS = 'LO_FI_BEATS';
export const SET_MELLOW_BEATS = 'SET_MELLOW_BEATS';
export const SET_BEATS_FOR_CODING = 'SET_BEATS_FOR_CODING';
export const SET_BEAT_ROUTES = 'SET_BEAT_ROUTES';